# ============================================================
# Plot Figures S.4--S.6
# Local-grid simulation results
# HCP-repro
#
# This script reads local-grid simulation results generated by
# simulation/reproduce_figureS4S5S6_data.R and creates heatmaps
# for local coverage and local prediction-region length.
#
# Each figure contains four panels comparing two choices of the
# number of local groups K.
#
# Input:
#   results/figureS4_local_data.csv
#   results/figureS5_local_data.csv
#   results/figureS6_local_data.csv
#
# Output:
#   results/figureS4_local_plot.pdf
#   results/figureS5_local_plot.pdf
#   results/figureS6_local_plot.pdf
#
# Note:
#   Update repo_dir below to the local path of this repository
#   before running the script.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(gridExtra)
  library(viridis)
})

# ------------------------------------------------------------
# User-adjustable paths
# ------------------------------------------------------------
repo_dir <- normalizePath(Sys.getenv("HCP_REPO_DIR", "."), mustWork = TRUE)
results_dir <- file.path(repo_dir, "results")

# ------------------------------------------------------------
# Read data
# ------------------------------------------------------------
input_files <- c(
  file.path(results_dir, "figureS4_local_data.csv"),
  file.path(results_dir, "figureS5_local_data.csv"),
  file.path(results_dir, "figureS6_local_data.csv")
)

dat <- dplyr::bind_rows(lapply(input_files, function(f) {
  if (!file.exists(f)) {
    stop("Cannot find file: ", f)
  }
  read.csv(f, stringsAsFactors = FALSE)
}))

required_cols <- c(
  "figure", "n", "scenario", "n_local_groups",
  "cell_id", "x2_mid", "x3_mid",
  "Mean_Cover", "SD_Cover", "Mean_Leng", "SD_Leng"
)

if (!all(required_cols %in% names(dat))) {
  stop(
    "Missing columns: ",
    paste(setdiff(required_cols, names(dat)), collapse = ", ")
  )
}

# ------------------------------------------------------------
# Helper: Plot one figure (4 panels)
# ------------------------------------------------------------
plot_one_local_figure <- function(dat_one) {
  
  k_values <- sort(unique(dat_one$n_local_groups))
  
  if (length(k_values) != 2L) {
    stop(
      "Each figure must contain exactly two n_local_groups values. Found: ",
      paste(k_values, collapse = ", ")
    )
  }
  
  k1 <- k_values[1]
  k2 <- k_values[2]
  
  df1 <- dat_one %>% filter(n_local_groups == k1)
  df2 <- dat_one %>% filter(n_local_groups == k2)
  
  # shared color scales
  cover_limits <- range(c(df1$Mean_Cover, df2$Mean_Cover), na.rm = TRUE)
  leng_limits  <- range(c(df1$Mean_Leng,  df2$Mean_Leng),  na.rm = TRUE)
  
  # -------------------------
  # Coverage plots
  # -------------------------
  p1 <- ggplot(df1, aes(x = x2_mid, y = x3_mid, fill = Mean_Cover)) +
    geom_tile(color = "white") +
    scale_fill_viridis(option = "D", limits = cover_limits) +
    labs(
      title = paste0("Local Coverage, K=", k1),
      x = expression(x[2]),
      y = expression(x[3]),
      fill = ""
    ) +
    theme_minimal(base_size = 8) +
    theme(plot.title = element_text(hjust = 0.5))
  
  p2 <- ggplot(df2, aes(x = x2_mid, y = x3_mid, fill = Mean_Cover)) +
    geom_tile(color = "white") +
    scale_fill_viridis(option = "D", limits = cover_limits) +
    labs(
      title = paste0("Local Coverage, K=", k2),
      x = expression(x[2]),
      y = NULL,
      fill = ""
    ) +
    theme_minimal(base_size = 8) +
    theme(plot.title = element_text(hjust = 0.5))
  
  # -------------------------
  # Length plots
  # -------------------------
  p3 <- ggplot(df1, aes(x = x2_mid, y = x3_mid, fill = Mean_Leng)) +
    geom_tile(color = "white") +
    scale_fill_viridis(option = "D", limits = leng_limits) +
    labs(
      title = paste0("Local Length, K=", k1),
      x = expression(x[2]),
      y = expression(x[3]),
      fill = ""
    ) +
    theme_minimal(base_size = 8) +
    theme(plot.title = element_text(hjust = 0.5))
  
  p4 <- ggplot(df2, aes(x = x2_mid, y = x3_mid, fill = Mean_Leng)) +
    geom_tile(color = "white") +
    scale_fill_viridis(option = "D", limits = leng_limits) +
    labs(
      title = paste0("Local Length, K=", k2),
      x = expression(x[2]),
      y = NULL,
      fill = ""
    ) +
    theme_minimal(base_size = 8) +
    theme(plot.title = element_text(hjust = 0.5))
  
  gridExtra::arrangeGrob(p1, p2, p3, p4, nrow = 2, ncol = 2)
}

# ------------------------------------------------------------
# Generate and save figures
# ------------------------------------------------------------
figure_files <- c(
  figureS4 = "figureS4_local_plot.pdf",
  figureS5 = "figureS5_local_plot.pdf",
  figureS6 = "figureS6_local_plot.pdf"
)

for (fid in names(figure_files)) {
  
  dat_one <- dat %>% filter(figure == fid)
  
  if (nrow(dat_one) == 0L) {
    warning("No data found for ", fid)
    next
  }
  
  cat("Plotting ", fid, "...\n", sep = "")
  
  p <- plot_one_local_figure(dat_one)
  
  ggsave(
    filename = file.path(results_dir, figure_files[[fid]]),
    plot = p,
    width = 7,
    height = 5
  )
}