# ============================================================
# Plot Figure S.1--S.3
# Conditional-coverage simulation results
# HCP-repro
#
# This script reads conditional-coverage simulation results
# generated by simulation/reproduce_figureS1S2S3_data.R and creates
# Figure S.1, Figure S.2, and Figure S.3 in the supplementary materials.
#
# Input:
#   results/figureS1_conditional_data.csv
#   results/figureS2_conditional_data.csv
#   results/figureS3_conditional_data.csv
#
# Output:
#   results/figureS1_conditional_plot.pdf
#   results/figureS2_conditional_plot.pdf
#   results/figureS3_conditional_plot.pdf
#
# Note:
#   Update repo_dir below to the local path of this repository
#   before running the script.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(gridExtra)
})

# ------------------------------------------------------------
# User-adjustable paths
# ------------------------------------------------------------
repo_dir <- normalizePath(Sys.getenv("HCP_REPO_DIR", "."), mustWork = TRUE)
results_dir <- file.path(repo_dir, "results")

# ------------------------------------------------------------
# Read data
# ------------------------------------------------------------
input_files <- c(
  file.path(results_dir, "figureS1_conditional_data.csv"),
  file.path(results_dir, "figureS2_conditional_data.csv"),
  file.path(results_dir, "figureS3_conditional_data.csv")
)

dat <- dplyr::bind_rows(lapply(input_files, function(f) {
  if (!file.exists(f)) {
    stop("Cannot find file: ", f)
  }
  read.csv(f, stringsAsFactors = FALSE)
}))

required_cols <- c(
  "figure", "n", "scenario", "n_local_groups", "x2",
  "Mean_Cover", "SD_Cover", "Mean_Leng", "SD_Leng"
)

if (!all(required_cols %in% names(dat))) {
  stop(
    "Missing columns: ",
    paste(setdiff(required_cols, names(dat)), collapse = ", ")
  )
}

# ------------------------------------------------------------
# Plotting helper functions
# ------------------------------------------------------------
cover_plot <- function(df, title) {
  ggplot(df, aes(x = x2)) +
    geom_line(aes(y = Mean_Cover), color = "blue") +
    geom_hline(yintercept = 0.9, linetype = "dashed", color = "red") +
    geom_ribbon(
      aes(
        ymin = Mean_Cover - 1.645 * SD_Cover,
        ymax = Mean_Cover + 1.645 * SD_Cover
      ),
      alpha = 0.2,
      fill = "blue"
    ) +
    labs(
      title = title,
      x = expression(x[2]),
      y = "Conditional Coverage"
    ) +
    theme_minimal(base_size = 8) +
    theme(plot.title = element_text(hjust = 0.5)) +
    scale_y_continuous(
      limits = c(0.6, 1.08),
      breaks = seq(0.6, 1.0, by = 0.1)
    )
}

leng_plot <- function(df, title) {
  ggplot(df, aes(x = x2)) +
    geom_line(aes(y = Mean_Leng), color = "blue") +
    geom_ribbon(
      aes(
        ymin = Mean_Leng - 3 * 1.645 * SD_Leng,
        ymax = Mean_Leng + 3 * 1.645 * SD_Leng
      ),
      alpha = 0.2,
      fill = "blue"
    ) +
    labs(
      title = title,
      x = expression(x[2]),
      y = "Conditional Length"
    ) +
    ylim(0, 35) +
    theme_minimal(base_size = 8) +
    theme(plot.title = element_text(hjust = 0.5))
}

# ------------------------------------------------------------
# Plot one figure in a 2 x 2 layout
# ------------------------------------------------------------
plot_one_figure <- function(dat_one) {
  k_values <- sort(unique(dat_one$n_local_groups))
  
  if (length(k_values) != 2L) {
    stop(
      "Each figure should contain exactly two n_local_groups values. Found: ",
      paste(k_values, collapse = ", ")
    )
  }
  
  k1 <- k_values[1]
  k2 <- k_values[2]
  
  df1 <- dat_one %>% filter(n_local_groups == k1)
  df2 <- dat_one %>% filter(n_local_groups == k2)
  
  p1 <- cover_plot(df1, paste0("K=", k1))
  p2 <- leng_plot(df1, paste0("K=", k1))
  p3 <- cover_plot(df2, paste0("K=", k2)) + labs(y = NULL)
  p4 <- leng_plot(df2, paste0("K=", k2)) + labs(y = NULL)
  
  gridExtra::arrangeGrob(p1, p3, p2, p4, ncol = 2)
}

# ------------------------------------------------------------
# Generate and save figures
# ------------------------------------------------------------
figure_files <- c(
  figureS1 = "figureS1_conditional_plot.pdf",
  figureS2 = "figureS2_conditional_plot.pdf",
  figureS3 = "figureS3_conditional_plot.pdf"
)

for (fid in names(figure_files)) {
  dat_one <- dat %>% filter(figure == fid)
  
  if (nrow(dat_one) == 0L) {
    warning("No data found for ", fid)
    next
  }
  
  p <- plot_one_figure(dat_one)
  
  ggsave(
    filename = file.path(results_dir, figure_files[[fid]]),
    plot = p,
    width = 5.5,
    height = 4
  )
}