# ============================================================
# Plot Figure S.10
# Pointwise benchmark comparison
# HCPclust-repro
#
# This script reads method-specific pointwise simulation results
# generated by simulation/reproduce_figureS10_data.R and creates
# the Figure S.10 boxplot in the supplementary materials. The figure
# compares HCP, DWR, LC, LMEM, and Oracle across simulation scenarios.
#
# Input:
#   results/figureS10_HCP_final_mat_n500.csv
#   results/figureS10_DWR_final_mat_n500.csv
#   results/figureS10_LC_final_mat_n500.csv
#   results/figureS10_LMEM_final_mat_n500.csv
#   results/figureS10_Oracle_final_mat_n500.csv
#
# Output:
#   results/figureS10_n500.pdf
#
# Note:
#   Update repo_dir below to the local path of this repository
#   before running the script.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(ggh4x)
})

# ------------------------------------------------------------
# User-adjustable paths
# ------------------------------------------------------------
repo_dir <- normalizePath("~/Desktop/HCPclust-repro", mustWork = TRUE)
results_dir <- file.path(repo_dir, "results")

# ------------------------------------------------------------
# Read results
# ------------------------------------------------------------
suffix <- "_n500"

HCP_final_mat <- read.csv(file.path(results_dir, paste0("figureS10_HCP_final_mat", suffix, ".csv")),
                          stringsAsFactors = FALSE)
DWR_final_mat <- read.csv(file.path(results_dir, paste0("figureS10_DWR_final_mat", suffix, ".csv")),
                          stringsAsFactors = FALSE)
LC_final_mat <- read.csv(file.path(results_dir, paste0("figureS10_LC_final_mat", suffix, ".csv")),
                         stringsAsFactors = FALSE)
LMEM_final_mat <- read.csv(file.path(results_dir, paste0("figureS10_LMEM_final_mat", suffix, ".csv")),
                           stringsAsFactors = FALSE)
Oracle_final_mat <- read.csv(file.path(results_dir, paste0("figureS10_Oracle_final_mat", suffix, ".csv")),
                             stringsAsFactors = FALSE)

# ------------------------------------------------------------
# Settings and labels
# ------------------------------------------------------------
settings_order <- c("Homo", "Heter", "Asym", "Bimo", "Bimo.fix")
setting_labels <- c(
  Homo = "Homo",
  Heter = "Heter",
  Asym = "Asym",
  Bimo = "Bimo",
  Bimo.fix = "Bimo-fix"
)

method_order <- c("HCP", "DWR", "LC", "LMEM", "Oracle")

method_list <- list(
  HCP = HCP_final_mat,
  DWR = DWR_final_mat,
  LC = LC_final_mat,
  LMEM = LMEM_final_mat,
  Oracle = Oracle_final_mat
)

# ------------------------------------------------------------
# Helper: group pointwise results before boxplot visualization
# ------------------------------------------------------------
group_mean <- function(x, K = 40, seed = 123) {
  stopifnot(is.numeric(x))
  N <- length(x)
  stopifnot(N %% K == 0)
  
  set.seed(seed)
  gid <- sample(rep(seq_len(K), each = N / K))
  as.numeric(tapply(x, gid, mean))
}

K <- 40
res_list <- list()

for (mtd in names(method_list)) {
  df <- method_list[[mtd]]
  
  need <- as.vector(rbind(
    paste0(settings_order, "_cov"),
    paste0(settings_order, "_len")
  ))
  
  if (!all(need %in% names(df))) {
    stop(
      "Missing columns in ", mtd, ": ",
      paste(setdiff(need, names(df)), collapse = ", ")
    )
  }
  
  for (s in settings_order) {
    res_list[[length(res_list) + 1L]] <- data.frame(
      Setting = s,
      Metric = "Coverage",
      Method = mtd,
      Group = seq_len(K),
      Value = group_mean(df[[paste0(s, "_cov")]], K = K),
      stringsAsFactors = FALSE
    )
    
    res_list[[length(res_list) + 1L]] <- data.frame(
      Setting = s,
      Metric = "Length",
      Method = mtd,
      Group = seq_len(K),
      Value = group_mean(df[[paste0(s, "_len")]], K = K),
      stringsAsFactors = FALSE
    )
  }
}

plot_df <- dplyr::bind_rows(res_list) %>%
  dplyr::mutate(
    Setting_raw = factor(Setting, levels = settings_order),
    Setting_lab = factor(
      Setting_raw,
      levels = settings_order,
      labels = setting_labels[settings_order]
    ),
    Metric = factor(Metric, levels = c("Coverage", "Length")),
    Method = factor(Method, levels = method_order)
  )

vline_df <- plot_df %>%
  dplyr::distinct(Setting_lab) %>%
  dplyr::mutate(
    Metric = factor("Coverage", levels = levels(plot_df$Metric)),
    xint = 0.9
  )

# ------------------------------------------------------------
# Plot
# ------------------------------------------------------------
desired_top_to_bottom <- c("HCP", "DWR", "LC", "LMEM", "Oracle")

p_s10 <- ggplot(plot_df, aes(x = Value, y = Method)) +
  scale_y_discrete(limits = rev(desired_top_to_bottom)) +
  
  geom_boxplot(
    width = 0.46,
    outlier.shape = NA,
    colour = "grey20",
    fill = "white",
    linewidth = 0.35
  ) +
  
  stat_summary(
    fun = mean,
    geom = "point",
    shape = 22,
    size = 1.15,
    stroke = 0.4,
    fill = "white",
    colour = "grey15"
  ) +
  
  geom_vline(
    data = vline_df,
    aes(xintercept = xint),
    colour = "#D73027",
    linewidth = 0.45
  ) +
  
  ggh4x::facet_grid2(
    rows = vars(Setting_lab),
    cols = vars(Metric),
    scales = "free_x",
    independent = "x",
    switch = "x"
  ) +
  
  theme_classic(base_size = 11) +
  theme(
    panel.border = element_rect(color = "grey25", fill = NA, linewidth = 0.45),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    
    strip.placement = "outside",
    strip.text.x = element_text(face = "bold", size = 11, color = "grey10"),
    strip.text.y = element_text(size = 10, face = "bold", angle = 270, color = "grey10"),
    strip.background.y = element_rect(fill = "grey90", colour = NA),
    strip.background.x = element_blank(),
    
    axis.line = element_blank(),
    axis.ticks = element_line(color = "grey25", linewidth = 0.35),
    axis.text = element_text(size = 8.5, color = "grey15"),
    axis.text.y = element_text(color = "grey10"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 12, face = "bold", color = "grey10"),
    
    panel.spacing.x = unit(1.35, "lines"),
    panel.spacing.y = unit(1.15, "lines"),
    plot.margin = margin(6, 8, 6, 6)
  ) +
  
  ggh4x::facetted_pos_scales(
    x = list(
      Metric == "Coverage" ~ scale_x_continuous(
        limits = c(0.45, 1.0),
        breaks = seq(0.5, 1.0, by = 0.1),
        labels = function(z) sprintf("%.2f", z),
        expand = expansion(mult = c(0.00, 0.02))
      )
    )
  )

print(p_s10)

# ------------------------------------------------------------
# Save figure
# ------------------------------------------------------------
ggsave(
  filename = file.path(results_dir, paste0("figureS10", suffix, ".pdf")),
  plot = p_s10,
  width = 6.5,
  height = 9.5
)