# ============================================================
# Plot Figure S.7
# Sample-size sensitivity simulation results
# HCP-repro
#
# This script reads sample-size sensitivity results generated by
# simulation/reproduce_figureS7_data.R and creates Figure S.7
# in the supplementary materials. The figure summarizes coverage
# deviation and average prediction-region length across simulation
# scenarios and sample sizes.
#
# Input:
#   results/figureS7_Homo_results.csv
#   results/figureS7_Heter_results.csv
#   results/figureS7_Asym_results.csv
#   results/figureS7_Bimo_results.csv
#   results/figureS7_Bimo-Fix_results.csv
#
# Output:
#   results/figureS7.pdf
#
# Note:
#   Update repo_dir below to the local path of this repository
#   before running the script.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(ggh4x)
})

# ------------------------------------------------------------
# User-adjustable paths
# ------------------------------------------------------------
repo_dir <- normalizePath(Sys.getenv("HCP_REPO_DIR", "."), mustWork = TRUE)
results_dir <- file.path(repo_dir, "results")

# ------------------------------------------------------------
# Settings
# ------------------------------------------------------------
n_values <- c(seq(100, 1500, by = 100))

files <- c(
  Homo = "figureS7_Homo_results.csv",
  Heter = "figureS7_Heter_results.csv",
  Asym = "figureS7_Asym_results.csv",
  Bimo = "figureS7_Bimo_results.csv",
  `Bimo-fix` = "figureS7_Bimo-Fix_results.csv"
)

setting_levels <- c("Homo", "Heter", "Asym", "Bimo", "Bimo-fix")

# ------------------------------------------------------------
# Helper functions for summarizing coverage and length
# ------------------------------------------------------------
wilson_ci <- function(k, n, conf.level = 0.90) {
  if (n == 0) {
    return(c(mean = NA_real_, low = NA_real_, high = NA_real_))
  }
  
  z <- qnorm(1 - (1 - conf.level) / 2)
  p <- k / n
  
  denom <- 1 + z^2 / n
  center <- (p + z^2 / (2 * n)) / denom
  half <- (z / denom) * sqrt(p * (1 - p) / n + z^2 / (4 * n^2))
  
  c(
    mean = center,
    low = pmax(0, center - half),
    high = pmin(1, center + half)
  )
}

summarize_one <- function(dat, n_values) {
  out <- data.frame(
    n = n_values,
    mean_cov = NA_real_,
    cov_low = NA_real_,
    cov_high = NA_real_,
    diff_cov = NA_real_,
    diff_low = NA_real_,
    diff_high = NA_real_,
    mean_len = NA_real_,
    len_low = NA_real_,
    len_high = NA_real_
  )
  
  for (i in seq_along(n_values)) {
    n_val <- n_values[i]
    
    cov_col <- paste0("cov_n", n_val)
    len_col <- paste0("len_n", n_val)
    
    if (!all(c(cov_col, len_col) %in% names(dat))) {
      stop("Missing columns: ", cov_col, " or ", len_col)
    }
    
    cv <- dat[[cov_col]]
    lv <- dat[[len_col]]
    
    k <- sum(cv == 1, na.rm = TRUE)
    n_eff <- sum(!is.na(cv))
    ci <- wilson_ci(k, n_eff, conf.level = 0.90)
    
    len_mean <- mean(lv, na.rm = TRUE)
    len_se <- sd(lv, na.rm = TRUE) / sqrt(sum(!is.na(lv)))
    
    out$mean_cov[i] <- ci["mean"]
    out$cov_low[i] <- ci["low"]
    out$cov_high[i] <- ci["high"]
    
    out$diff_cov[i] <- ci["mean"] - 0.9
    out$diff_low[i] <- ci["low"] - 0.9
    out$diff_high[i] <- ci["high"] - 0.9
    
    out$mean_len[i] <- len_mean
    out$len_low[i] <- len_mean - 1.645 * len_se
    out$len_high[i] <- len_mean + 1.645 * len_se
  }
  
  out
}

theme_s7 <- function(base_size = 11) {
  theme_classic(base_size = base_size) +
    theme(
      panel.border = element_rect(color = "grey35", fill = NA, linewidth = 0.45),
      panel.grid.major.y = element_line(color = "grey88", linewidth = 0.28),
      panel.grid.major.x = element_line(color = "grey94", linewidth = 0.22),
      panel.grid.minor = element_blank(),
      
      axis.line = element_blank(),
      axis.ticks = element_line(color = "grey35", linewidth = 0.35),
      axis.text = element_text(size = base_size - 2.2, color = "grey15"),
      axis.title.x = element_text(
        size = base_size + 1,
        face = "bold",
        margin = margin(t = 8)
      ),
      axis.title.y = element_blank(),
      
      strip.placement = "outside",
      strip.text.y.right = element_text(
        size = 10,
        face = "bold",
        angle = 270,
        color = "grey10"
      ),
      strip.background.y = element_rect(fill = "grey92", colour = NA),
      strip.text.x = element_text(face = "bold", size = 11, color = "grey10"),
      strip.background.x = element_blank(),
      
      panel.spacing.x = unit(1.45, "lines"),
      panel.spacing.y = unit(1.05, "lines"),
      plot.margin = margin(8, 8, 8, 8)
    )
}

# ------------------------------------------------------------
# Read and summarize data
# ------------------------------------------------------------
summary_df <- dplyr::bind_rows(lapply(names(files), function(st) {
  fpath <- file.path(results_dir, files[[st]])
  
  if (!file.exists(fpath)) {
    stop("File not found: ", fpath)
  }
  
  dat <- read.csv(fpath, stringsAsFactors = FALSE)
  df <- summarize_one(dat, n_values = n_values)
  df$Setting <- st
  df
})) %>%
  dplyr::mutate(
    Setting = factor(Setting, levels = setting_levels)
  )

plot_df <- summary_df %>%
  dplyr::select(
    Setting, n,
    diff_cov, diff_low, diff_high,
    mean_len, len_low, len_high
  ) %>%
  tidyr::pivot_longer(
    cols = c(diff_cov, mean_len),
    names_to = "Metric",
    values_to = "Value"
  ) %>%
  dplyr::mutate(
    Metric = factor(
      Metric,
      levels = c("diff_cov", "mean_len"),
      labels = c("Coverage deviation", "Average length")
    )
  )

cov_band_df <- summary_df %>%
  dplyr::transmute(
    Setting,
    n,
    Metric = factor(
      "Coverage deviation",
      levels = c("Coverage deviation", "Average length")
    ),
    ymin = diff_low,
    ymax = diff_high
  )

len_band_df <- summary_df %>%
  dplyr::transmute(
    Setting,
    n,
    Metric = factor(
      "Average length",
      levels = c("Coverage deviation", "Average length")
    ),
    ymin = len_low,
    ymax = len_high
  )

# ------------------------------------------------------------
# Plot
# ------------------------------------------------------------
p_s7 <- ggplot(plot_df, aes(x = n, y = Value)) +
  geom_ribbon(
    data = cov_band_df,
    aes(x = n, ymin = ymin, ymax = ymax),
    inherit.aes = FALSE,
    fill = "grey70",
    alpha = 0.35
  ) +
  geom_ribbon(
    data = len_band_df,
    aes(x = n, ymin = ymin, ymax = ymax),
    inherit.aes = FALSE,
    fill = "grey70",
    alpha = 0.35
  ) +
  geom_hline(
    data = data.frame(
      Metric = factor("Coverage deviation",
                      levels = c("Coverage deviation", "Average length"))
    ),
    aes(yintercept = 0),
    inherit.aes = FALSE,
    linewidth = 0.35,
    linetype = "dashed",
    colour = "grey45"
  ) +
  geom_line(
    linewidth = 0.45,
    lineend = "round",
    colour = "grey35"
  ) +
  geom_point(
    shape = 21,
    size = 1.0,
    stroke = 0.55,
    fill = "white",
    colour = "grey10"
  ) +
  scale_x_continuous(
    breaks = pretty(n_values, n = 5),
    labels = pretty(n_values, n = 5)
  ) +
  labs(x = "Sample size (n)") +
  ggh4x::facet_grid2(
    rows = vars(Setting),
    cols = vars(Metric),
    scales = "free_y",
    independent = "y",
    switch = "x"
  ) +
  ggh4x::facetted_pos_scales(
    y = list(
      Metric == "Coverage deviation" ~ scale_y_continuous(
        limits = c(-0.1, 0.1),
        breaks = seq(-0.1, 0.1, by = 0.05),
        labels = function(z) sprintf("%.2f", z),
        expand = expansion(mult = c(0.03, 0.03))
      ),
      Metric == "Average length" ~ scale_y_continuous(
        expand = expansion(mult = c(0.12, 0.16))
      )
    )
  ) +
  theme_s7(base_size = 11)

print(p_s7)

# ------------------------------------------------------------
# Save figure
# ------------------------------------------------------------
ggsave(
  filename = file.path(results_dir, "figureS7.pdf"),
  plot = p_s7,
  width = 6.0,
  height = 9.0
)