# ============================================================
# Plot Figure S.8 and Figure S.9
# Sensitivity analysis for B and S
# HCPclust-repro
#
# This script reads sensitivity-analysis results generated by
# simulation/reproduce_figureS8S9_data.R and creates Figure S.8
# and Figure S.9 in the supplementary materials. Figure S.8
# studies sensitivity to the number of calibration subsamples B,
# and Figure S.9 studies sensitivity to the number of repeated
# subject-level splits S.
#
# Input:
#   results/figureS8_sensitivity_B_data.csv
#   results/figureS9_sensitivity_S_data.csv
#
# Output:
#   results/figureS8_sensitivity_B.pdf
#   results/figureS9_sensitivity_S.pdf
#
# Note:
#   Update repo_dir below to the local path of this repository
#   before running the script.
# ============================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(gridExtra)
})

# ------------------------------------------------------------
# User-adjustable paths
# ------------------------------------------------------------
repo_dir <- normalizePath("~/Desktop/HCPclust-repro", mustWork = TRUE)
results_dir <- file.path(repo_dir, "results")

# ------------------------------------------------------------
# Read data
# ------------------------------------------------------------
figureS8_data <- read.csv(
  file.path(results_dir, "figureS8_sensitivity_B_data.csv"),
  stringsAsFactors = FALSE
)

figureS9_data <- read.csv(
  file.path(results_dir, "figureS9_sensitivity_S_data.csv"),
  stringsAsFactors = FALSE
)

# ------------------------------------------------------------
# Plot marginal coverage
# ------------------------------------------------------------
plot_coverage_panel <- function(dat, n_value, x_var, x_lab) {
  dat_sub <- dat %>%
    dplyr::filter(n == n_value)
  
  ggplot(dat_sub, aes(x = .data[[x_var]])) +
    geom_line(aes(y = coverage), color = "blue") +
    geom_hline(yintercept = 0.9, linetype = "dashed", color = "red") +
    labs(
      x = x_lab,
      y = "Marginal Coverage",
      title = paste("n =", n_value)
    ) +
    ylim(0.8, 1.0) +
    theme_minimal(base_size = 7.5) +
    theme(
      plot.title = element_text(hjust = 0.5)
    )
}

# ------------------------------------------------------------
# Plot marginal length with standard-error bands
# ------------------------------------------------------------
plot_length_panel <- function(dat, n_value, x_var, x_lab) {
  dat_sub <- dat %>%
    dplyr::filter(n == n_value) %>%
    dplyr::mutate(
      length_lo = length - 1.645 * length_se,
      length_hi = length + 1.645 * length_se
    )
  
  ggplot(dat_sub) +
    geom_line(aes(x = .data[[x_var]], y = length), color = "blue") +
    geom_ribbon(
      aes(
        x = .data[[x_var]],
        ymin = length_lo,
        ymax = length_hi
      ),
      fill = "blue",
      alpha = 0.2
    ) +
    labs(
      x = x_lab,
      y = "Marginal Length",
      title = paste("n =", n_value)
    ) +
    theme_minimal(base_size = 7.5) +
    theme(
      plot.title = element_text(hjust = 0.5)
    ) +
    ylim(13, 22)
}

# ------------------------------------------------------------
# Assemble six-panel figure
# ------------------------------------------------------------
make_sensitivity_figure <- function(dat, x_var, x_lab) {
  n_values <- sort(unique(dat$n))
  
  if (length(n_values) != 3L) {
    stop("Expected exactly three sample sizes in the sensitivity data.")
  }
  
  p1 <- plot_coverage_panel(dat, n_values[1], x_var, x_lab)
  p2 <- plot_coverage_panel(dat, n_values[2], x_var, x_lab)
  p3 <- plot_coverage_panel(dat, n_values[3], x_var, x_lab)
  p4 <- plot_length_panel(dat, n_values[1], x_var, x_lab)
  p5 <- plot_length_panel(dat, n_values[2], x_var, x_lab)
  p6 <- plot_length_panel(dat, n_values[3], x_var, x_lab)
  
  gridExtra::grid.arrange(
    p1, p2, p3,
    p4, p5, p6,
    nrow = 2,
    ncol = 3
  )
}

# ------------------------------------------------------------
# Create Figure S.8
# ------------------------------------------------------------
figureS8_plot <- make_sensitivity_figure(
  dat = figureS8_data,
  x_var = "B",
  x_lab = "B"
)

ggsave(
  filename = file.path(results_dir, "figureS8_sensitivity_B.pdf"),
  plot = figureS8_plot,
  width = 6,
  height = 4
)

# ------------------------------------------------------------
# Create Figure S.9
# ------------------------------------------------------------
figureS9_plot <- make_sensitivity_figure(
  dat = figureS9_data,
  x_var = "S",
  x_lab = "S"
)

ggsave(
  filename = file.path(results_dir, "figureS9_sensitivity_S.pdf"),
  plot = figureS9_plot,
  width = 6,
  height = 4
)